### PR TITLE
Rails upgrade to 3.2.22 (security upgrade)

### PR DESCRIPTION
**Pull request by shadowbq**
Rails upgrade to 3.2.22
Travis CI test pushed to 2.0 2.1 and 2.2

### CODE REVIEW

**Comment by jbbarth** [comment]
Thanks for the proposal. Do you actually use cartoque? It has been unmaintained for 1 year now, since I switched to a new job and my previous team has switched to more "mainstream" tools. I thought nobody was using it since there are many things that are strongly tied to my old work environment and not generic enough...

**Comment by shadowbq** [comment]
I am using it only for the rest api and backend. I'm building out some integration with some other apps  and docker containing this app.. I will pushing this up to Rails 4 then Rails 5. I would like to maintain this if you want to turn it over.

Do you want to convert this to a github org? (cartoque)  and move it out from your jbbarth/ ?

**Comment by jbbarth** [comment]
Fine by me, thanks for the proposal! I move cartoque to the cartoque org where I invited you. I let you take care of those technical upgrades, don't hesitate to open PR(s) if you want my opinion on something, I'll be happy to help you.

**Comment by shadowbq** [comment]
Can you give me write access to the main cartoque repo?

**Comment by jbbarth** [comment]
Yes, sorry, thought it was the case. Done.

**Pull request merged**
